import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  // inital value of the count as 0
  // we get this value back in an array, where the first value is the count
  // this is called array destructuring

  const [messageData, setMessageData] = useState({
    messageObject: {
      message: "",
      metadata: Date.now(),
    },
  });

  const [messageList, setMessageList] = useState([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
          }}
        >
          <input
            type="text"
            style={{
              background: "white",
              border: "2px solid black",
              fontSize: "16px",
              padding: "16px",
              cursor: "pointer",
            }}
            value={messageData.messageObject.message}
            onChange={(e) =>
              setMessageData((prevState) => {
                return {
                  ...prevState,
                  messageObject: { message: e.target.value },
                };
              })
            }
          ></input>
          <button
            style={{
              background: "white",
              border: "2px solid black",
              fontSize: "16px",
              padding: "16px",
              cursor: "pointer",
            }}
            onClick={() => {
              setMessageData((prevObject) => ({
                ...prevObject,
                messageObject: { message: "", metadata: Date.now() },
              }));
              setMessageList([
                ...messageList,
                messageData.messageObject.message,
              ]);
            }}
          >
            Add to list
          </button>
        </div>
        {!!messageList.length && (
          <ul
            style={{
              background: "white",
              border: "2px solid black",
              fontSize: "16px",
              padding: "16px",
            }}
          >
            {messageList.map((message) => (
              <li
                style={{
                  background: "white",
                  border: "2px solid black",
                  fontSize: "16px",
                  padding: "16px",
                }}
                key={message}
              >
                {message}
              </li>
            ))}
          </ul>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
